---
- name: test playbook
  hosts: "{{ target | default('localhost') }}"
  vars:
    playbook_path: "{{ (lookup('file', '/proc/self/cmdline', errors='warn') | regex_replace('\u0000',' ')).split() }}"
    pattern: '[a-zA-Z0-9_-]*[.][a-z]*'

  tasks:
  - name: debug playbook_path
    debug:
      msg: "{{ playbook_path }}"
  - name: set_fact
    set_fact:
      playbook_name: "{{ playbook_path | map('regex_search', pattern) | select('string') | list }}"
  - name: debug set_fact
    debug:
      msg: "{{ playbook_name }}"
