---
- name: test playbook (basic linux example)
  hosts: "{{ target | default('localhost') }}"
  vars:
    playbook_path: "{{ (lookup('file', '/proc/self/cmdline', errors='warn') | regex_replace('\u0000', ' ')).split() }}"
    pattern: '[a-zA-Z0-9_-]*[.]ya?ml'

  tasks:
  - name: set_fact playbook_name
    set_fact:
      playbook_name: "{{ playbook_path | map('regex_search', pattern) | select('string') | list }}"
  - name: debug playbook_name
    debug:
      msg: "{{ playbook_name }}"
